// <auto-generated />
namespace EasyPay.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserWallet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserWallet));
        
        string IMigrationMetadata.Id
        {
            get { return "201303212001140_UserWallet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
